### ISSUE TITLE
Ability to change window title?

### ISSUE THREAD

**Issue by StrikerMan780** [RobLoach/nuklear_console#108]
Apologies for asking so many questions, but is there a way to change the window title while you switch between pages in a menu? Wanting to have the title bar change as one switches through the Main Menu, Options, Save/Load, etc.

**Comment by RobLoach** [comment]
Use nk_console_render_window() instead and change the title paraameter?
```c
const char* title = "Window Title"; 
nk_console_render_window(console, title, nk_rect(0, 0, (float)screen->width, (float)screen->height), NK_WINDOW_TITLE);
```

nk_console_render() is meant to be used within a nk_begin()/end(), where as render_window takes control over the nk_begin stuffs.

**Comment by StrikerMan780** [comment]
I mean, that's what I'm using, but the menu setup is only done once at program init, so I'm wondering how I'm going to make it pass the title to it.

```
nk_console_render_window(console, title, nk_rect(menu_x, menu_y - (scale_y(300, 480) / 2.0f), menu_width, scale_y(300, 480)), NK_WINDOW_TITLE | NK_WINDOW_BORDER);
```

**Comment by StrikerMan780** [comment]
Hmm, I got around it by setting up an onclicked event, which sets the parent menu itself, and sets the title variable to the label of the button.

**Comment by RobLoach** [comment]
pew pew pew pew pew pew pew pew pew BEEP!

**Comment by RobLoach** [comment]
Sounds like you got it fixed up. Thanks!
