### ISSUE TITLE
Buggy text alignment in comboboxes.

### ISSUE THREAD

**Issue by StrikerMan780** [RobLoach/nuklear_console#112]
Here's a video demonstrating a bizarre bug with text centering with comboboxes:
https://shadowmavericks.com/files/ShareX/tfury_2024-09-17_14-51-51.mp4

![image](https://shadowmavericks.com/files/ShareX/tfury_2024-09-17_14-59-23.png)

Potentially related to: https://github.com/Immediate-Mode-UI/Nuklear/issues/646#issuecomment-2350096385

or perhaps the check against message width, is against the whole string, rather than the split portion, leaving blank space.

**Comment by StrikerMan780** [comment]
Yeah, something doesn't look right with how it's calculating the length here:
```c
    // Add all the sub-page buttons
    const char* button_text_start = items_separated_by_separator;
    int text_length = 0;
    for (int i = 0; items_separated_by_separator[i] != 0; i++) {
        text_length++;
        if (items_separated_by_separator[i] == (char)separator) {
            nk_console_button_onclick(combobox, button_text_start, &nk_console_combobox_button_click)
                ->label_length = text_length - 1;
            text_length = 0;
            button_text_start = items_separated_by_separator + i + 1;
        }
    }

    // Add the last item
    nk_console_button_onclick(combobox, button_text_start, &nk_console_combobox_button_click)
        ->label_length = text_length;
```

**Comment by StrikerMan780** [comment]
Another possibility is that the "text length" function is having difficulty due to lack of a null terminator.

**Comment by RobLoach** [comment]
Interesting idea... If there's no null-terminator, you can also set the `console->length_length`.

Another thing to consider could how your renderer gets the rendered text width?

**Comment by StrikerMan780** [comment]
Yeah, it was my fault. My text width function wasn't being fed the "len" value of the width callback in Nuklear.
