### ISSUE TITLE
Support rows/grids of widgets

### ISSUE THREAD

**Issue by brianwatling** [RobLoach/nuklear_console#21]
Currently all widgets start a new layout row and therefore all navigation is either up or down (handled by nk_console_check_up_down). Some UIs, for example an inventory screen, need a grid of elements with both vertical and horizontal navigation.

One approach to accomplish this could be to create a new widget that adds left and right navigation. This approach provides loose coupling with the rest of the nk_console system - other widgets need not know they're part of a row and everything should work just fine.

The API might look something like:
```c
// Start a new row with 2 columns.
nk_console* row = nk_console_row_begin(parent, /*columns=*/2);
// Add child widgets to 'row' as usual.
nk_console_button(row, "First");
nk_console_button(row, "Second");
// End the row. Internally the row's children will be hidden from the usual parent/child logic and the row widget will be responsible for rendering everything correctly.
nk_console_row_end(row);
```

I'm prototyping an implementation of the above. My plan is to attempt to implement it without making any/minimal changes to the existing nk_console logic. Interested to hear feedback on the approach - let me know if you think this is feasible or have opinions on a different direction

**Comment by RobLoach** [comment]
That would be great. One good use case for this would be an on-screen keyboard :+1:

Had an attempt at it with https://github.com/RobLoach/nuklear_console/pull/9

**Comment by RobLoach** [comment]
Also note, there is a `int columns` that we could use for some of this. Not sure how helpful it would be though.
https://github.com/RobLoach/nuklear_console/blob/master/nuklear_console.h#L73

You can see an example of it used in the checkbox:
https://github.com/RobLoach/nuklear_console/blob/master/nuklear_console_checkbox.h#L26-L28
