### ISSUE TITLE
Better callback support

### ISSUE THREAD

**Issue by brianwatling** [RobLoach/nuklear_console#69]
`onchange` and other callbacks should have a richer feature set. Per-widget `user_data` allowed callbacks to have / act on some context but it was limited and potentially interfered with any user data the user otherwise may have wanted to set. #66 moved `user_data` to be only for top-level console objects which further limits what's possible for callbacks - now there's no way for an onchange callback to dynamically know what widget was changed.

Example use case: layered sprite UI using nk_console_progress use old style user_data
```c
layer_names = {"pants", "shirt", "hair"}
for (int i = 0; i < num_layers; ++i) {
  c = nk_console_progress(parent, layer_names[i], &current[i], num_options[i]);
  c->onchange = &handle_layer_change;
  c->user_data = &layer_data[i];
}
```
A more featured callback system should allow for arbitrary data to be passed to the callback along with support for an destructor (both data and destructor should be optional). Ideally the system should support binding a C++ lambda via templates (maybe this can even be provided inside a `#ifdef __cplusplus` guard)

```c++
// New C function to set onchange event to a basic/static callback like current implementaiton.
void nk_console_set_onchange(nk_console* console, nk_console_event onchange);

typedef void (*nk_console_destructor_callback)(void* user_data);

// New C function to set an advanced callback.
void nk_console_set_onchange_advanced(nk_console* console, nk_console_event onchange, void* user_data, nk_console_destructor_callback dtor);

// C++ wrapper to create a callback that wraps the given lambda. The lambda will be cleaned up when `console` is destroyed or a new onchange is set.
template<typename T>
void nk_console_set_onchange(nk_console* console, T&& lambda)
```

**Comment by brianwatling** [comment]
I'll take a pass at this

**Comment by RobLoach** [comment]
Ah, you're right. Having a user_data per widget does give you a lot of control over what you put in there. Think reverting that change is a good idea? https://github.com/RobLoach/nuklear_console/pull/70

Having a more powerful event system would be awesome. Was also thinking we could turn all events into a cvector to allow for multiple event calls, along with different types of events dynamically.

``` c
nk_console_add_event(nk_console* console, enum nk_console_event_type type, nk_console_event event, void* user_data, nk_console_destructor_callback dtor);
```

**Comment by brianwatling** [comment]
> could turn all events into a cvector to allow for multiple event calls

IMHO this might be best left to the user  to decide. I can't think of any cases off the top of my head where I might want that so I'd lean towards not making event handlers a list by default. If we use a scheme like in #71 then it may be possible to transparently support yet not always make everything a list:

```c
void nk_console_set_onchange_handler(nk_console* widget, nk_console_event_handler onchange) {
  // overwrite the handler as in #71 
}

void nk_console_multi_event_call(nk_console_event_data data, nk_console* widget) {
  // Here we assume data.user is a cvector of nk_console_event_handler that we should loop through
}

void nk_console_multi_event_destroy(nk_console_event_data data, nk_console* widget) {
  // Here we assume data.user is a cvector of nk_console_event_handler that we should loop through
}

void nk_console_add_onchange_handler(nk_console* widget, nk_console_event_handler onchange) {
  if (!widget->onchange.callback) {
      // Case 1: no existing handler. Just call nk_console_set_onchange_handler
  } else if (widget->onchange.callback != &nk_console_multi_event_call) {
      // Case 2: exactly one existing handler. Need to convert this to a list of handlers
  } else {
      // Case 3: already a list of handlers. Append to the list. 
  }
}
```
