### ISSUE TITLE
Event System Improvements

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/nuklear_console#78]
@brianwatling following discussion here so we don't lose it. Thoughts on this? Goal is to consolidate most event systems into just one `nk_console_event_handler* events`.

- Make a `enum nk_console_event_type` with `DESTROY`, `CHANGE`, and `CLICK`
- Add a `enum nk_console_event_type` to `nk_console_event_handler`
- Have `nk_console_event_handler* events` in `nk_console` as a cvector for all events
- Move `nk_console_button_data::onchange` to the new events pattern
- Move `nk_console::destroy` to the new events pattern
- Keep `render` outside of the event system to keep performance a priority
- Re-work the invoke events to take a `enum nk_console_event_type`
- Rather than `nk_console_onchange(widget)`, call `nk_console_invoke(widget, NK_CONSOLE_EVENT_TYPE_CHANGE)`... or something?
- Update `nk_console_set_onchange_handler()` to `nk_console_add_event_handler()`
- Update `nk_console_set_onchange()` to `nk_console_add_event`

**Comment by brianwatling** [comment]
I think your suggestion to have an enum for the event type seems reasonable. That'll help reduce the API surface for event handling.

> Have nk_console_event_handler* events in nk_console as a cvector for all events

Are you suggesting all events are stored in a single array that's scanned when an event is triggered? Seems like a clean approach and performance shouldn't be a concern given events are triggered relatively infrequently - so I think this is decent way to implement this
